### ISSUE TITLE
Implement RFC 2617, WWW-Authenicate header when status is 401

### ISSUE THREAD

**Issue by samip5** [ViRb3/authelia-basic-auth-2fa#7]
This would benefit users of example VLC.

Reference: https://tools.ietf.org/html/rfc2617#section-3.2.1

**Comment by samip5** [comment]
@ViRb3 I mention you so you will for sure get a notification. :)

**Comment by ViRb3** [comment]
Hey there, thanks for taking interest in this project.

If you are following the official Authelia [proxy integration guide](https://www.authelia.com/docs/deployment/supported-proxies/nginx.html), you should have a statement like this (nginx):
```nginx
error_page 401 =302 https://auth.website.com/?rd=$target_url;
```
This will redirect the user to the Authelia login page if they are not authenticated. By merging your PR, two things will happen;
1. The header won't travel back to the user unless explicitly defined in the reverse proxy.
2. If the header is set to travel back to the user, it will prompt basic auth, conflicting with the redirection statement above.

Since for most use cases we want people to use the Authelia login portal, I don't think that it's a good idea to add this header in authelia-basic-2fa. Instead, it can be added as needed in the reverse proxy configuration. Here's how I match the user agent to decide whether the user should be redirected (if using a browser) or basic auth should be prompted (VLC, etc.):

```nginx
location @basic_auth_prompt {
    internal;
    add_header "WWW-Authenticate" "Basic realm=\"Restricted Content\"" always;
    return 401;
}

location / {
	if ($http_user_agent ~* "vlc|kodi") {
		error_page 401 = @basic_auth_prompt;
	}
	...
}
```
Please let me know if there's a use case that I'm not accounting for.

**Comment by samip5** [comment]
Hey there, 

The use case you're not accounting for is Traefik version 2, its Integration guide is here: https://www.authelia.com/docs/deployment/supported-proxies/traefik2.x.html. 

I have built the container with my PR changes and verified that the header does get added for 401 responses,  but I don't know why VLC is still not prompting for details like it should.  I want that to work.  I also think that the RFC would be good to follow in this application. 

The basic proxy does not redirect from a 401 response,  so should it?

**Comment by ViRb3** [comment]
Hey. As I mentioned before, I don't have any experience with Traefik, so unfortunately I can't help with configuring it. What I'm trying to say, though, is that you have to choose one of two responses to unauthorized access:
- Redirect to login page (302)
- Show basic auth prompt (401 + header)

You can't have both at the same time, or at least I'm unaware how. If you force the header from `authelia-basic-2fa`, then you can't have redirection. So, in my opinion, the best solution is to delegate the redirect/basic auth decision to the reverse proxy, like I described above. Again, I don't know how to do this in Traefik, but it should be possible. You are always welcome to use nginx instead or to contribute documentation on how to set up Traefik. If you have a better idea I am all ears.

**Comment by samip5** [comment]
> Hey. As I mentioned before, I don't have any experience with Traefik, so unfortunately I can't help with configuring it. What I'm trying to say, though, is that you have to choose one of two responses to unauthorized access:
> 
> * Redirect to login page (302)
> * Show basic auth prompt (401 + header)
> 
> You can't have both at the same time, or at least I'm unaware how. If you force the header from `authelia-basic-2fa`, then you can't have redirection. So, in my opinion, the best solution is to delegate the redirect/basic auth decision to the reverse proxy, like I described above. Again, I don't know how to do this in Traefik, but it should be possible. You are always welcome to use nginx instead or to contribute documentation on how to set up Traefik. If you have a better idea I am all ears.

Even without the prompt, I'm not redirected to the auth, via the container and Traefik so cannot comment on that.

**Comment by ViRb3** [comment]
There must be something wrong with your setup, redirection works as expected for me with nginx. You will probably have to tell Traefik to handle 401 as a redirection to the portal.

**Comment by samip5** [comment]
That's entirely possible, but point is that it should be implemented, but could be a passeable parameter for it or something like that so a user can choose it, or a ENV variable to set which one is used.

**Comment by samip5** [comment]
It seems that there is going to be support for this in authelia directly.

Ref: authelia/authelia/pull/1563

**Comment by ViRb3** [comment]
Thanks for the heads up! I'll make sure to update this proxy to support that.

**Comment by ViRb3** [comment]
After a more thorough read, it seems like this update does not require any change on our side. The new update allows reverse proxies to use a new query parameter `/verify?auth=basic` to use the `Authorization` header instead of `Proxy-Authorization` to when authenticating. We currently re-write the `Authorization` header as `Proxy-Authorization`, and it will continue to work, both across old and new versions.

**Comment by ColCh** [comment]
@ViRb3 so, looks like header is not sent in current main branch? (sorry for necropost)
https://github.com/ViRb3/authelia-basic-2fa/blob/7a3e0f8d3324482c590e596949687c36969482de/clientHandler.go#L172

for people who is searching in Google: example how to add WWW-Authenticate header, in Caddyfile

```
	@foo host foo.local
	handle @foo {
        forward_auth * foo_auth:8080 {
            uri /
            copy_headers Remote-User Remote-Groups Remote-Name Remote-Email
            header_up Host {upstream_hostport}

            @bad status 4xx
            handle_response @bad {
                header ?WWW-Authenticate "Basic realm=\"foo\""
                respond {rp.status_text} {rp.status_code}
            }
        }
        reverse_proxy foo:8080
    }
```
